/*
 * Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
 * 
 * On Tue Oct 30 18:01:59 UTC 2018
 * 
 * To automatically register this VPI wrapper with a Verilog simulator use:
 *     #include "vpi_wrapper_fileCreate_C.h"
 *     void (*vlog_startup_routines[])() = { fileCreate_C_vpi_register, 0u };
 * 
 * For a Verilog simulator which requires a .tab file, use the following entry:
 * $imported_fileCreate_C call=fileCreate_C_calltf size=1 acc=rw:%TASK
 * 
 * For a Verilog simulator which requires a .sft file, use the following entry:
 * $imported_fileCreate_C vpiSysFuncSized 1 unsigned
 */
#include <stdlib.h>
#include <vpi_user.h>
#include "bdpi.h"

/* the type of the wrapped function */
char fileCreate_C();

/* VPI wrapper function */
PLI_INT32 fileCreate_C_calltf(PLI_BYTE8 *user_data)
{
  vpiHandle hCall;
  char vpi_result;
  vpiHandle *handle_array;
  
  /* retrieve handle array */
  hCall = vpi_handle(vpiSysTfCall, 0);
  handle_array = vpi_get_userdata(hCall);
  if (handle_array == NULL)
  {
    vpiHandle hArgList;
    hArgList = vpi_iterate(vpiArgument, hCall);
    handle_array = malloc(sizeof(vpiHandle) * 1u);
    handle_array[0u] = hCall;
    vpi_put_userdata(hCall, handle_array);
    vpi_free_object(hArgList);
  }
  
  /* create return value */
  make_vpi_result(handle_array[0u], &vpi_result, DIRECT);
  
  /* call the imported C function */
  vpi_result = fileCreate_C();
  
  /* copy out return value */
  put_vpi_result(handle_array[0u], &vpi_result, DIRECT);
  vpi_free_object(hCall);
  
  return 0;
}

/* sft: $imported_fileCreate_C vpiSysFuncSized 1 unsigned */

/* tab: $imported_fileCreate_C call=fileCreate_C_calltf size=1 acc=rw:%TASK */

PLI_INT32 fileCreate_C_sizetf(PLI_BYTE8 *user_data)
{
  return 1u;
}

/* VPI wrapper registration function */
void fileCreate_C_vpi_register()
{
  s_vpi_systf_data tf_data;
  
  /* Fill in registration data */
  tf_data.type = vpiSysFunc;
  tf_data.sysfunctype = vpiSizedFunc;
  tf_data.tfname = "$imported_fileCreate_C";
  tf_data.calltf = fileCreate_C_calltf;
  tf_data.compiletf = 0u;
  tf_data.sizetf = fileCreate_C_sizetf;
  tf_data.user_data = "$imported_fileCreate_C";
  
  /* Register the function with VPI */
  vpi_register_systf(&tf_data);
}
