/*
 * Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
 * 
 * On Tue Oct 30 18:01:59 UTC 2018
 * 
 */
#ifndef __vpi_wrapper_fileAppend_C_h__
#define __vpi_wrapper_fileAppend_C_h__

#include <vpi_user.h>

/* registration function */
void fileAppend_C_vpi_register();

/* VPI wrapper function */
PLI_INT32 fileAppend_C_calltf(PLI_BYTE8 *user_data);

#endif /* ifndef __vpi_wrapper_fileAppend_C_h__ */
