/*
 * Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
 * 
 * On Sat Nov 10 01:20:25 UTC 2018
 * 
 */
extern "C" {
  char fileAppend_C(unsigned long long );
  char fileCreate_C();
}
