/*
 * Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
 * 
 * On Sat Nov 10 01:20:25 UTC 2018
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkTest.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkTest::MODEL_mkTest()
{
  mkTest_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkTest()
{
  MODEL_mkTest *model = new MODEL_mkTest();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkTest &INST_top = *((MOD_mkTest *)(instance_ptr));
	 tUInt8 DEF_INST_top_INST_mem_DEF_CAN_FIRE_RL_findMemSize;
	 tUInt8 DEF_INST_top_INST_mem_DEF_WILL_FIRE_RL_findMemSize;
	 tUInt8 DEF_INST_top_INST_mem_DEF_CAN_FIRE_RL_dumpData;
	 tUInt8 DEF_INST_top_INST_mem_DEF_WILL_FIRE_RL_dumpData;
	 tUInt8 DEF_INST_top_DEF_jj_delay_count_read__34_EQ_189_35_AND_start_wi_ETC___d436;
	 tUInt8 DEF_INST_top_DEF_NOT_abort_whas__00_22_OR_NOT_abort_wget__01_23_ETC___d442;
	 tUInt8 DEF_INST_top_DEF_NOT_abort_whas__00_22_OR_NOT_abort_wget__01_23_ETC___d438;
	 tUInt8 DEF_INST_top_DEF_jj_delay_count_read__34_EQ_189_35_AND_NOT_star_ETC___d461;
	 tUInt8 DEF_INST_top_DEF_abort_whas__00_AND_abort_wget__01_02_OR_state__ETC___d470;
	 tUInt8 DEF_INST_top_DEF_abort_whas__00_AND_abort_wget__01_02_OR_state__ETC___d474;
	 tUInt8 DEF_INST_top_DEF_NOT_start_wire_whas__03_04_OR_NOT_start_wire_w_ETC___d407;
	 tUInt8 DEF_INST_top_DEF_abort_whas__00_AND_abort_wget__01___d402;
	 tUInt8 DEF_INST_top_DEF_start_wire_whas__03_AND_start_wire_wget__05___d426;
	 tUInt8 DEF_INST_top_DEF_NOT_abort_whas__00_22_OR_NOT_abort_wget__01_23___d424;
	 tUInt8 DEF_INST_top_DEF_abort_whas__00_AND_abort_wget__01_02_OR_state__ETC___d432;
	 tUInt8 DEF_INST_top_DEF_probTb_state_73_EQ_4___d274;
	 tUInt8 DEF_INST_top_DEF_state_mkFSMstate_read__30_EQ_4___d437;
	 tUInt8 DEF_INST_top_DEF_state_mkFSMstate_read__30_EQ_5___d441;
	 tUInt8 DEF_INST_top_DEF_jj_delay_count_read__34_EQ_189___d435;
	 tUInt8 DEF_INST_top_DEF_connection_word_counter_7_EQ_0_8_OR_mem_RDY_pu_ETC___d20;
	 tUInt8 DEF_INST_top_DEF_IF_mem_get1_connection_letter_counter_PLUS_1_1_ETC___d21;
	 tUInt8 DEF_INST_top_DEF_mem_RDY_put____d19;
	 tUInt8 DEF_INST_top_DEF_abort_wget____d401;
	 tUInt8 DEF_INST_top_DEF_abort_whas____d400;
	 tUInt8 DEF_INST_top_DEF_start_reg__h19362;
	 tUInt8 DEF_INST_top_DEF_running__h19467;
	 tUInt8 DEF_INST_top_DEF_start_wire_wget____d405;
	 tUInt8 DEF_INST_top_DEF_start_wire_whas____d403;
	 tUInt8 DEF_INST_top_DEF_start_reg_1__h17513;
	 tUInt8 DEF_INST_top_DEF_state_fired__h17515;
	 tUInt8 DEF_INST_top_DEF_connection_state__h353;
	 tUInt8 DEF_INST_top_DEF_probTb_state__h1886;
	 tUInt8 DEF_INST_top_DEF_state_mkFSMstate_read____d430;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_connection_directMemConnections;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_connection_dumpMem;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_connection_dumpMem;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_connection_directMemConnections;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_probTb_movingDown;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_probTb_movingDown;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_start_reg__dreg_update;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_start_reg__dreg_update;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_state_handle_abort;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_state_handle_abort;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_state_fired__dreg_update;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_state_fired__dreg_update;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_state_every;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_state_every;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_restart;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_restart;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l22c15;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l23c10;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_l24c11;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_d_init_np;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_action_np;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_idle_l21c13;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_idle_l21c13;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_idle_l21c13_1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_idle_l21c13_1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_fsm_start;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_fsm_start;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_auto_start;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_auto_start;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_auto_finish;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_auto_finish;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_8;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_8;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_9;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_9;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_10;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_10;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE___me_check_11;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE___me_check_11;
	 DEF_INST_top_DEF_state_mkFSMstate_read____d430 = INST_top.INST_state_mkFSMstate.METH_read();
	 DEF_INST_top_DEF_abort_whas____d400 = INST_top.INST_abort.METH_whas();
	 DEF_INST_top_DEF_abort_wget____d401 = INST_top.INST_abort.METH_wget();
	 DEF_INST_top_DEF_NOT_abort_whas__00_22_OR_NOT_abort_wget__01_23___d424 = !DEF_INST_top_DEF_abort_whas____d400 || !DEF_INST_top_DEF_abort_wget____d401;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_d_init_np = DEF_INST_top_DEF_NOT_abort_whas__00_22_OR_NOT_abort_wget__01_23___d424 && DEF_INST_top_DEF_state_mkFSMstate_read____d430 == (tUInt8)3u;
	 INST_top.DEF_WILL_FIRE_RL_action_d_init_np = DEF_INST_top_DEF_CAN_FIRE_RL_action_d_init_np;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l23c10 = INST_top.INST_mem.METH_dumpCompletion() && (DEF_INST_top_DEF_NOT_abort_whas__00_22_OR_NOT_abort_wget__01_23___d424 && DEF_INST_top_DEF_state_mkFSMstate_read____d430 == (tUInt8)1u);
	 INST_top.DEF_WILL_FIRE_RL_action_l23c10 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l23c10;
	 DEF_INST_top_DEF_probTb_state__h1886 = INST_top.INST_probTb_state.METH_read();
	 DEF_INST_top_DEF_probTb_state_73_EQ_4___d274 = DEF_INST_top_DEF_probTb_state__h1886 == (tUInt8)4u;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l24c11 = !DEF_INST_top_DEF_probTb_state_73_EQ_4___d274 && (DEF_INST_top_DEF_NOT_abort_whas__00_22_OR_NOT_abort_wget__01_23___d424 && DEF_INST_top_DEF_state_mkFSMstate_read____d430 == (tUInt8)2u);
	 INST_top.DEF_WILL_FIRE_RL_action_l24c11 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l24c11;
	 INST_top.DEF_jj_delay_count_read____d434 = INST_top.INST_jj_delay_count.METH_read();
	 DEF_INST_top_DEF_state_fired__h17515 = INST_top.INST_state_fired.METH_read();
	 DEF_INST_top_DEF_start_reg_1__h17513 = INST_top.INST_start_reg_1.METH_read();
	 DEF_INST_top_DEF_start_reg__h19362 = INST_top.INST_start_reg.METH_read();
	 DEF_INST_top_DEF_running__h19467 = INST_top.INST_running.METH_read();
	 DEF_INST_top_DEF_jj_delay_count_read__34_EQ_189___d435 = (INST_top.DEF_jj_delay_count_read____d434) == (tUInt8)189u;
	 DEF_INST_top_DEF_state_mkFSMstate_read__30_EQ_5___d441 = DEF_INST_top_DEF_state_mkFSMstate_read____d430 == (tUInt8)5u;
	 DEF_INST_top_DEF_state_mkFSMstate_read__30_EQ_4___d437 = DEF_INST_top_DEF_state_mkFSMstate_read____d430 == (tUInt8)4u;
	 DEF_INST_top_DEF_abort_whas__00_AND_abort_wget__01___d402 = DEF_INST_top_DEF_abort_whas____d400 && DEF_INST_top_DEF_abort_wget____d401;
	 DEF_INST_top_DEF_abort_whas__00_AND_abort_wget__01_02_OR_state__ETC___d432 = DEF_INST_top_DEF_abort_whas__00_AND_abort_wget__01___d402 || DEF_INST_top_DEF_state_mkFSMstate_read____d430 == (tUInt8)0u;
	 DEF_INST_top_DEF_abort_whas__00_AND_abort_wget__01_02_OR_state__ETC___d470 = ((DEF_INST_top_DEF_abort_whas__00_AND_abort_wget__01_02_OR_state__ETC___d432 || (DEF_INST_top_DEF_jj_delay_count_read__34_EQ_189___d435 && DEF_INST_top_DEF_state_mkFSMstate_read__30_EQ_4___d437)) || (DEF_INST_top_DEF_jj_delay_count_read__34_EQ_189___d435 && DEF_INST_top_DEF_state_mkFSMstate_read__30_EQ_5___d441)) && (!DEF_INST_top_DEF_start_reg_1__h17513 || DEF_INST_top_DEF_state_fired__h17515);
	 DEF_INST_top_DEF_abort_whas__00_AND_abort_wget__01_02_OR_state__ETC___d474 = DEF_INST_top_DEF_abort_whas__00_AND_abort_wget__01_02_OR_state__ETC___d470 && !DEF_INST_top_DEF_start_reg__h19362;
	 DEF_INST_top_DEF_CAN_FIRE_RL_auto_finish = DEF_INST_top_DEF_running__h19467 && DEF_INST_top_DEF_abort_whas__00_AND_abort_wget__01_02_OR_state__ETC___d474;
	 DEF_INST_top_DEF_WILL_FIRE_RL_auto_finish = DEF_INST_top_DEF_CAN_FIRE_RL_auto_finish;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_np = !DEF_INST_top_DEF_jj_delay_count_read__34_EQ_189___d435 && (DEF_INST_top_DEF_NOT_abort_whas__00_22_OR_NOT_abort_wget__01_23___d424 && (DEF_INST_top_DEF_state_mkFSMstate_read__30_EQ_4___d437 || DEF_INST_top_DEF_state_mkFSMstate_read__30_EQ_5___d441));
	 INST_top.DEF_WILL_FIRE_RL_action_np = DEF_INST_top_DEF_CAN_FIRE_RL_action_np;
	 DEF_INST_top_DEF_CAN_FIRE_RL_auto_start = DEF_INST_top_DEF_abort_whas__00_AND_abort_wget__01_02_OR_state__ETC___d474 && !DEF_INST_top_DEF_running__h19467;
	 DEF_INST_top_DEF_WILL_FIRE_RL_auto_start = DEF_INST_top_DEF_CAN_FIRE_RL_auto_start;
	 INST_top.DEF_x__h1255 = INST_top.INST_connection_word_counter.METH_read();
	 INST_top.DEF_x__h1601 = INST_top.INST_connection_letter_counter.METH_read();
	 INST_top.DEF_mem_get0_connection_letter_counter_BITS_4_TO_0___d4 = (tUInt8)((tUInt8)31u & INST_top.INST_mem.METH_get0(INST_top.DEF_x__h1601));
	 INST_top.DEF_x__h1597 = 16383u & ((INST_top.DEF_x__h1601) + 1u);
	 INST_top.DEF_mem_get1_connection_letter_counter_PLUS_1_1_2__ETC___d13 = (tUInt8)((tUInt8)31u & INST_top.INST_mem.METH_get1(INST_top.DEF_x__h1597));
	 DEF_INST_top_DEF_connection_state__h353 = INST_top.INST_connection_state.METH_read();
	 DEF_INST_top_DEF_mem_RDY_put____d19 = INST_top.INST_mem.METH_RDY_put();
	 INST_top.DEF_connection_word_counter_7_EQ_0___d18 = (INST_top.DEF_x__h1255) == 0u;
	 DEF_INST_top_DEF_connection_word_counter_7_EQ_0_8_OR_mem_RDY_pu_ETC___d20 = INST_top.DEF_connection_word_counter_7_EQ_0___d18 || DEF_INST_top_DEF_mem_RDY_put____d19;
	 switch (INST_top.DEF_mem_get1_connection_letter_counter_PLUS_1_1_2__ETC___d13) {
	 case (tUInt8)26u:
	 case (tUInt8)27u:
	   DEF_INST_top_DEF_IF_mem_get1_connection_letter_counter_PLUS_1_1_ETC___d21 = DEF_INST_top_DEF_connection_word_counter_7_EQ_0_8_OR_mem_RDY_pu_ETC___d20;
	   break;
	 default:
	   DEF_INST_top_DEF_IF_mem_get1_connection_letter_counter_PLUS_1_1_ETC___d21 = DEF_INST_top_DEF_mem_RDY_put____d19;
	 }
	 INST_top.DEF_mem_get0_connection_letter_counter_BITS_4_TO_0_ETC___d8 = (INST_top.DEF_mem_get0_connection_letter_counter_BITS_4_TO_0___d4) == (tUInt8)28u;
	 INST_top.DEF_mem_get0_connection_letter_counter_BITS_4_TO_0_ETC___d5 = (INST_top.DEF_mem_get0_connection_letter_counter_BITS_4_TO_0___d4) == (tUInt8)26u;
	 INST_top.DEF_mem_get0_connection_letter_counter_BITS_4_TO_0_ETC___d6 = (INST_top.DEF_mem_get0_connection_letter_counter_BITS_4_TO_0___d4) == (tUInt8)27u;
	 DEF_INST_top_DEF_CAN_FIRE_RL_connection_directMemConnections = (INST_top.INST_mem.METH_RDY_get0() && (((INST_top.DEF_mem_get0_connection_letter_counter_BITS_4_TO_0_ETC___d5 || INST_top.DEF_mem_get0_connection_letter_counter_BITS_4_TO_0_ETC___d6) || INST_top.DEF_mem_get0_connection_letter_counter_BITS_4_TO_0_ETC___d8) || (INST_top.INST_mem.METH_RDY_get1() && DEF_INST_top_DEF_IF_mem_get1_connection_letter_counter_PLUS_1_1_ETC___d21))) && DEF_INST_top_DEF_connection_state__h353 == (tUInt8)3u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_connection_directMemConnections = DEF_INST_top_DEF_CAN_FIRE_RL_connection_directMemConnections;
	 DEF_INST_top_DEF_CAN_FIRE_RL_connection_dumpMem = INST_top.INST_mem.METH_RDY_nodeDump() && DEF_INST_top_DEF_connection_state__h353 == (tUInt8)0u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_connection_dumpMem = DEF_INST_top_DEF_CAN_FIRE_RL_connection_dumpMem;
	 DEF_INST_top_DEF_CAN_FIRE_RL_fsm_start = DEF_INST_top_DEF_abort_whas__00_AND_abort_wget__01_02_OR_state__ETC___d470 && DEF_INST_top_DEF_start_reg__h19362;
	 DEF_INST_top_DEF_WILL_FIRE_RL_fsm_start = DEF_INST_top_DEF_CAN_FIRE_RL_fsm_start;
	 INST_top.DEF_x__h2788 = INST_top.INST_probTb_nextAddr.METH_read();
	 INST_top.DEF_mem_get3_probTb_nextAddr_58___d259 = INST_top.INST_mem.METH_get3(INST_top.DEF_x__h2788);
	 INST_top.DEF_probTb_previousLetter__h2114 = INST_top.INST_probTb_previousLetter.METH_read();
	 INST_top.DEF_mem_get3_probTb_nextAddr_58_59_BIT_19___d260 = (tUInt8)((tUInt8)1u & ((INST_top.DEF_mem_get3_probTb_nextAddr_58___d259) >> 19u));
	 INST_top.DEF_probTb_previousLetter_63_EQ_27___d266 = (INST_top.DEF_probTb_previousLetter__h2114) == (tUInt8)27u;
	 INST_top.DEF_probTb_previousLetter_63_EQ_26___d264 = (INST_top.DEF_probTb_previousLetter__h2114) == (tUInt8)26u;
	 INST_top.DEF_NOT_mem_get3_probTb_nextAddr_58_59_BIT_19_60___d261 = !(INST_top.DEF_mem_get3_probTb_nextAddr_58_59_BIT_19___d260);
	 DEF_INST_top_DEF_CAN_FIRE_RL_probTb_movingDown = (INST_top.INST_mem.METH_RDY_get3() && (INST_top.DEF_NOT_mem_get3_probTb_nextAddr_58_59_BIT_19_60___d261 || (INST_top.INST_mem.METH_RDY_get2() && ((!(INST_top.DEF_probTb_previousLetter_63_EQ_26___d264) && !(INST_top.DEF_probTb_previousLetter_63_EQ_27___d266)) || DEF_INST_top_DEF_mem_RDY_put____d19)))) && DEF_INST_top_DEF_probTb_state_73_EQ_4___d274;
	 DEF_INST_top_DEF_WILL_FIRE_RL_probTb_movingDown = DEF_INST_top_DEF_CAN_FIRE_RL_probTb_movingDown && !DEF_INST_top_DEF_WILL_FIRE_RL_connection_directMemConnections;
	 DEF_INST_top_DEF_CAN_FIRE_RL_restart = (DEF_INST_top_DEF_start_reg_1__h17513 && !DEF_INST_top_DEF_state_fired__h17515) && DEF_INST_top_DEF_NOT_abort_whas__00_22_OR_NOT_abort_wget__01_23___d424;
	 DEF_INST_top_DEF_WILL_FIRE_RL_restart = DEF_INST_top_DEF_CAN_FIRE_RL_restart;
	 DEF_INST_top_DEF_CAN_FIRE_RL_start_reg__dreg_update = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_start_reg__dreg_update = DEF_INST_top_DEF_CAN_FIRE_RL_start_reg__dreg_update;
	 DEF_INST_top_DEF_CAN_FIRE_RL_state_every = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_state_every = DEF_INST_top_DEF_CAN_FIRE_RL_state_every;
	 DEF_INST_top_DEF_CAN_FIRE_RL_state_fired__dreg_update = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_state_fired__dreg_update = DEF_INST_top_DEF_CAN_FIRE_RL_state_fired__dreg_update;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_10 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_10 = DEF_INST_top_DEF_CAN_FIRE___me_check_10;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_11 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_11 = DEF_INST_top_DEF_CAN_FIRE___me_check_11;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_8 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_8 = DEF_INST_top_DEF_CAN_FIRE___me_check_8;
	 DEF_INST_top_DEF_CAN_FIRE___me_check_9 = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE___me_check_9 = DEF_INST_top_DEF_CAN_FIRE___me_check_9;
	 INST_top.INST_mem.DEF_mem_state__h348 = INST_top.INST_mem.INST_mem_state.METH_read();
	 DEF_INST_top_INST_mem_DEF_CAN_FIRE_RL_findMemSize = (INST_top.INST_mem.DEF_mem_state__h348) == (tUInt8)2u;
	 DEF_INST_top_INST_mem_DEF_WILL_FIRE_RL_findMemSize = DEF_INST_top_INST_mem_DEF_CAN_FIRE_RL_findMemSize;
	 DEF_INST_top_INST_mem_DEF_CAN_FIRE_RL_dumpData = (INST_top.INST_mem.DEF_mem_state__h348) == (tUInt8)0u;
	 DEF_INST_top_INST_mem_DEF_WILL_FIRE_RL_dumpData = DEF_INST_top_INST_mem_DEF_CAN_FIRE_RL_dumpData;
	 if (INST_top.DEF_WILL_FIRE_RL_action_d_init_np)
	   INST_top.RL_action_d_init_np();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l23c10)
	   INST_top.RL_action_l23c10();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l24c11)
	   INST_top.RL_action_l24c11();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_auto_finish)
	   INST_top.RL_auto_finish();
	 if (INST_top.DEF_WILL_FIRE_RL_action_np)
	   INST_top.RL_action_np();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_auto_start)
	   INST_top.RL_auto_start();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_connection_directMemConnections)
	   INST_top.RL_connection_directMemConnections();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_probTb_movingDown)
	   INST_top.RL_probTb_movingDown();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_connection_dumpMem)
	   INST_top.RL_connection_dumpMem();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_restart)
	   INST_top.RL_restart();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_9)
	   INST_top.__me_check_9();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_10)
	   INST_top.__me_check_10();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_11)
	   INST_top.__me_check_11();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_fsm_start)
	   INST_top.RL_fsm_start();
	 DEF_INST_top_DEF_start_wire_whas____d403 = INST_top.INST_start_wire.METH_whas();
	 DEF_INST_top_DEF_start_wire_wget____d405 = INST_top.INST_start_wire.METH_wget();
	 DEF_INST_top_DEF_start_wire_whas__03_AND_start_wire_wget__05___d426 = DEF_INST_top_DEF_start_wire_whas____d403 && DEF_INST_top_DEF_start_wire_wget____d405;
	 DEF_INST_top_DEF_NOT_abort_whas__00_22_OR_NOT_abort_wget__01_23_ETC___d438 = DEF_INST_top_DEF_NOT_abort_whas__00_22_OR_NOT_abort_wget__01_23___d424 && DEF_INST_top_DEF_state_mkFSMstate_read__30_EQ_4___d437;
	 DEF_INST_top_DEF_NOT_abort_whas__00_22_OR_NOT_abort_wget__01_23_ETC___d442 = DEF_INST_top_DEF_NOT_abort_whas__00_22_OR_NOT_abort_wget__01_23___d424 && DEF_INST_top_DEF_state_mkFSMstate_read__30_EQ_5___d441;
	 DEF_INST_top_DEF_jj_delay_count_read__34_EQ_189_35_AND_start_wi_ETC___d436 = DEF_INST_top_DEF_jj_delay_count_read__34_EQ_189___d435 && DEF_INST_top_DEF_start_wire_whas__03_AND_start_wire_wget__05___d426;
	 DEF_INST_top_DEF_CAN_FIRE_RL_action_l22c15 = (((DEF_INST_top_DEF_NOT_abort_whas__00_22_OR_NOT_abort_wget__01_23___d424 || DEF_INST_top_DEF_start_wire_whas__03_AND_start_wire_wget__05___d426) && DEF_INST_top_DEF_connection_state__h353 == (tUInt8)1u) && (((DEF_INST_top_DEF_start_wire_whas__03_AND_start_wire_wget__05___d426 && DEF_INST_top_DEF_abort_whas__00_AND_abort_wget__01_02_OR_state__ETC___d432) || (DEF_INST_top_DEF_jj_delay_count_read__34_EQ_189_35_AND_start_wi_ETC___d436 && DEF_INST_top_DEF_NOT_abort_whas__00_22_OR_NOT_abort_wget__01_23_ETC___d438)) || (DEF_INST_top_DEF_jj_delay_count_read__34_EQ_189_35_AND_start_wi_ETC___d436 && DEF_INST_top_DEF_NOT_abort_whas__00_22_OR_NOT_abort_wget__01_23_ETC___d442))) && !(((DEF_INST_top_DEF_CAN_FIRE_RL_action_np || DEF_INST_top_DEF_CAN_FIRE_RL_action_d_init_np) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l24c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l23c10)) || (DEF_INST_top_DEF_CAN_FIRE_RL_connection_dumpMem || DEF_INST_top_DEF_CAN_FIRE_RL_connection_directMemConnections));
	 INST_top.DEF_WILL_FIRE_RL_action_l22c15 = DEF_INST_top_DEF_CAN_FIRE_RL_action_l22c15;
	 DEF_INST_top_DEF_NOT_start_wire_whas__03_04_OR_NOT_start_wire_w_ETC___d407 = !DEF_INST_top_DEF_start_wire_whas____d403 || !DEF_INST_top_DEF_start_wire_wget____d405;
	 DEF_INST_top_DEF_jj_delay_count_read__34_EQ_189_35_AND_NOT_star_ETC___d461 = DEF_INST_top_DEF_jj_delay_count_read__34_EQ_189___d435 && DEF_INST_top_DEF_NOT_start_wire_whas__03_04_OR_NOT_start_wire_w_ETC___d407;
	 DEF_INST_top_DEF_CAN_FIRE_RL_idle_l21c13 = (DEF_INST_top_DEF_jj_delay_count_read__34_EQ_189_35_AND_NOT_star_ETC___d461 && DEF_INST_top_DEF_NOT_abort_whas__00_22_OR_NOT_abort_wget__01_23_ETC___d438) && !((DEF_INST_top_DEF_CAN_FIRE_RL_action_np || DEF_INST_top_DEF_CAN_FIRE_RL_action_d_init_np) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l24c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l23c10));
	 DEF_INST_top_DEF_WILL_FIRE_RL_idle_l21c13 = DEF_INST_top_DEF_CAN_FIRE_RL_idle_l21c13;
	 DEF_INST_top_DEF_CAN_FIRE_RL_idle_l21c13_1 = (DEF_INST_top_DEF_jj_delay_count_read__34_EQ_189_35_AND_NOT_star_ETC___d461 && DEF_INST_top_DEF_NOT_abort_whas__00_22_OR_NOT_abort_wget__01_23_ETC___d442) && !((DEF_INST_top_DEF_CAN_FIRE_RL_action_np || DEF_INST_top_DEF_CAN_FIRE_RL_action_d_init_np) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l24c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l23c10));
	 DEF_INST_top_DEF_WILL_FIRE_RL_idle_l21c13_1 = DEF_INST_top_DEF_CAN_FIRE_RL_idle_l21c13_1;
	 DEF_INST_top_DEF_CAN_FIRE_RL_state_handle_abort = (DEF_INST_top_DEF_abort_whas__00_AND_abort_wget__01___d402 && DEF_INST_top_DEF_NOT_start_wire_whas__03_04_OR_NOT_start_wire_w_ETC___d407) && !(((DEF_INST_top_DEF_CAN_FIRE_RL_action_np || DEF_INST_top_DEF_CAN_FIRE_RL_action_d_init_np) || (DEF_INST_top_DEF_CAN_FIRE_RL_action_l24c11 || DEF_INST_top_DEF_CAN_FIRE_RL_action_l23c10)) || DEF_INST_top_DEF_CAN_FIRE_RL_restart);
	 DEF_INST_top_DEF_WILL_FIRE_RL_state_handle_abort = DEF_INST_top_DEF_CAN_FIRE_RL_state_handle_abort;
	 if (INST_top.DEF_WILL_FIRE_RL_action_l22c15)
	   INST_top.RL_action_l22c15();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_idle_l21c13_1)
	   INST_top.RL_idle_l21c13_1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_start_reg__dreg_update)
	   INST_top.RL_start_reg__dreg_update();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_state_handle_abort)
	   INST_top.RL_state_handle_abort();
	 if (DEF_INST_top_DEF_WILL_FIRE___me_check_8)
	   INST_top.__me_check_8();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_idle_l21c13)
	   INST_top.RL_idle_l21c13();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_state_every)
	   INST_top.RL_state_every();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_state_fired__dreg_update)
	   INST_top.RL_state_fired__dreg_update();
	 if (DEF_INST_top_INST_mem_DEF_WILL_FIRE_RL_dumpData)
	   INST_top.INST_mem.RL_dumpData();
	 if (DEF_INST_top_INST_mem_DEF_WILL_FIRE_RL_findMemSize)
	   INST_top.INST_mem.RL_findMemSize();
	 INST_top.INST_state_fired_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_state_overlap_pw.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_state_set_pw.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_abort.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_start_reg_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_start_wire.clk((tUInt8)1u, (tUInt8)1u);
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_mem.INST_mem_state.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mem.INST_mem_counter.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mem.INST_sizeCounter.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mem.INST_dumpState.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_connection_letter_counter.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_connection_word_counter.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_connection_state.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_connection_wordTypeAddr.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_connection_letterOffset.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_probTb_nextAddr.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_probTb_state.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_probTb_resetAddr.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_probTb_nextAddrOffset.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_probTb_previousLetter.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_start_reg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_start_reg_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_jj_delay_count.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_state_mkFSMstate.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_state_fired.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_state_can_overlap.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_running.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkTest::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkTest_instance = new MOD_mkTest(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkTest_instance->INST_mem.set_clk_0)("CLK");
  (mkTest_instance->INST_start_wire.set_clk_0)("CLK");
  (mkTest_instance->INST_start_reg_2.set_clk_0)("CLK");
  (mkTest_instance->INST_abort.set_clk_0)("CLK");
  (mkTest_instance->INST_state_set_pw.set_clk_0)("CLK");
  (mkTest_instance->INST_state_overlap_pw.set_clk_0)("CLK");
  (mkTest_instance->INST_state_fired_1.set_clk_0)("CLK");
  (mkTest_instance->set_clk_0)("CLK");
}
void MODEL_mkTest::destroy_model()
{
  delete mkTest_instance;
  mkTest_instance = NULL;
}
void MODEL_mkTest::reset_model(bool asserted)
{
  (mkTest_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkTest::get_instance()
{
  return mkTest_instance;
}

/* Fill in version numbers */
void MODEL_mkTest::get_version(unsigned int *year,
			       unsigned int *month,
			       char const **annotation,
			       char const **build)
{
  *year = 2016u;
  *month = 7u;
  *annotation = "beta1";
  *build = "34806";
}

/* Get the model creation time */
time_t MODEL_mkTest::get_creation_time()
{
  
  /* Sat Nov 10 01:20:25 UTC 2018 */
  return 1541812825llu;
}

/* Control run-time licensing */
tUInt64 MODEL_mkTest::skip_license_check()
{
  return 0llu;
}

/* State dumping function */
void MODEL_mkTest::dump_state()
{
  (mkTest_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkTest & mkTest_backing(tSimStateHdl simHdl)
{
  static MOD_mkTest *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkTest(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkTest::dump_VCD_defs()
{
  (mkTest_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkTest::dump_VCD(tVCDDumpType dt)
{
  (mkTest_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkTest_backing(sim_hdl));
}
