/*
 * Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
 * 
 * On Sat May  5 03:00:08 UTC 2018
 * 
 */

/* Generation options: */
#ifndef __mkCounterTest_h__
#define __mkCounterTest_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkCounterTest module */
class MOD_mkCounterTest : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt32> INST_counter;
 
 /* Constructor */
 public:
  MOD_mkCounterTest(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
  tUInt32 DEF__read__h46;
 
 /* Rules */
 public:
 
 /* Methods */
 public:
  void METH_setValue(tUInt32 ARG_setValue_val);
  tUInt8 METH_RDY_setValue();
  void METH_increment(tUInt32 ARG_increment_inc);
  tUInt8 METH_RDY_increment();
  tUInt32 METH_readVal();
  tUInt8 METH_RDY_readVal();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkCounterTest &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkCounterTest &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkCounterTest &backing);
};

#endif /* ifndef __mkCounterTest_h__ */
