/*
 * Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
 * 
 * On Sat May  5 03:00:08 UTC 2018
 * 
 */
#include "bluesim_primitives.h"
#include "mkCounterTest.h"


/* Constructor */
MOD_mkCounterTest::MOD_mkCounterTest(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_counter(simHdl, "counter", this, 10u, 0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u)
{
  symbol_count = 1u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkCounterTest::init_symbols_0()
{
  init_symbol(&symbols[0u], "counter", SYM_MODULE, &INST_counter);
}


/* Rule actions */


/* Methods */

void MOD_mkCounterTest::METH_setValue(tUInt32 ARG_setValue_val)
{
  INST_counter.METH_write(ARG_setValue_val);
}

tUInt8 MOD_mkCounterTest::METH_RDY_setValue()
{
  tUInt8 DEF_CAN_FIRE_setValue;
  tUInt8 PORT_RDY_setValue;
  DEF_CAN_FIRE_setValue = (tUInt8)1u;
  PORT_RDY_setValue = DEF_CAN_FIRE_setValue;
  return PORT_RDY_setValue;
}

void MOD_mkCounterTest::METH_increment(tUInt32 ARG_increment_inc)
{
  tUInt32 DEF_x__h85;
  DEF__read__h46 = INST_counter.METH_read();
  DEF_x__h85 = 1023u & (DEF__read__h46 + ARG_increment_inc);
  INST_counter.METH_write(DEF_x__h85);
}

tUInt8 MOD_mkCounterTest::METH_RDY_increment()
{
  tUInt8 DEF_CAN_FIRE_increment;
  tUInt8 PORT_RDY_increment;
  DEF_CAN_FIRE_increment = (tUInt8)1u;
  PORT_RDY_increment = DEF_CAN_FIRE_increment;
  return PORT_RDY_increment;
}

tUInt32 MOD_mkCounterTest::METH_readVal()
{
  tUInt32 PORT_readVal;
  DEF__read__h46 = INST_counter.METH_read();
  PORT_readVal = DEF__read__h46;
  return PORT_readVal;
}

tUInt8 MOD_mkCounterTest::METH_RDY_readVal()
{
  tUInt8 DEF_CAN_FIRE_readVal;
  tUInt8 PORT_RDY_readVal;
  DEF_CAN_FIRE_readVal = (tUInt8)1u;
  PORT_RDY_readVal = DEF_CAN_FIRE_readVal;
  return PORT_RDY_readVal;
}


/* Reset routines */

void MOD_mkCounterTest::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_counter.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkCounterTest::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkCounterTest::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_counter.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkCounterTest::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 3u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "_read__h46", 10u);
  num = INST_counter.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkCounterTest::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkCounterTest &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkCounterTest::vcd_defs(tVCDDumpType dt, MOD_mkCounterTest &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 10u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF__read__h46) != DEF__read__h46)
      {
	vcd_write_val(sim_hdl, num, DEF__read__h46, 10u);
	backing.DEF__read__h46 = DEF__read__h46;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF__read__h46, 10u);
      backing.DEF__read__h46 = DEF__read__h46;
    }
}

void MOD_mkCounterTest::vcd_prims(tVCDDumpType dt, MOD_mkCounterTest &backing)
{
  INST_counter.dump_VCD(dt, backing.INST_counter);
}
