/*
 * Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
 * 
 * On Sat Apr 14 17:24:02 UTC 2018
 * 
 */

/* Generation options: */
#ifndef __mkCounter_h__
#define __mkCounter_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkCounter module */
class MOD_mkCounter : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Wire<tUInt8> INST_decrement_called;
  MOD_Wire<tUInt8> INST_increment_called;
  MOD_Reg<tUInt8> INST_value;
 
 /* Constructor */
 public:
  MOD_mkCounter(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_NOT_increment_called_whas___d7;
  tUInt8 DEF_NOT_decrement_called_whas___d3;
  tUInt8 DEF_decrement_called_whas____d2;
  tUInt8 DEF_increment_called_whas____d1;
 
 /* Local definitions */
 private:
  tUInt8 DEF_x__h182;
 
 /* Rules */
 public:
  void RL_do_increment();
  void RL_do_decrement();
 
 /* Methods */
 public:
  tUInt8 METH_read();
  tUInt8 METH_RDY_read();
  void METH_load(tUInt8 ARG_load_newval);
  tUInt8 METH_RDY_load();
  void METH_increment();
  tUInt8 METH_RDY_increment();
  void METH_decrement();
  tUInt8 METH_RDY_decrement();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkCounter &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkCounter &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkCounter &backing);
};

#endif /* ifndef __mkCounter_h__ */
