/*
 * Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
 * 
 * On Thu May  3 12:22:02 UTC 2018
 * 
 */

/* Generation options: */
#ifndef __mktbCounter2_h__
#define __mktbCounter2_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mktbCounter2 module */
class MOD_mktbCounter2 : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Wire<tUInt8> INST_abort;
  MOD_Wire<tUInt8> INST_counter_decrement_value;
  MOD_Wire<tUInt8> INST_counter_increment_value;
  MOD_Reg<tUInt8> INST_counter_value;
  MOD_Reg<tUInt8> INST_running;
  MOD_Reg<tUInt8> INST_start_reg;
  MOD_Reg<tUInt8> INST_start_reg_1;
  MOD_Wire<tUInt8> INST_start_reg_2;
  MOD_Wire<tUInt8> INST_start_wire;
  MOD_Reg<tUInt8> INST_state_can_overlap;
  MOD_Reg<tUInt8> INST_state_fired;
  MOD_Wire<tUInt8> INST_state_fired_1;
  MOD_ConfigReg<tUInt8> INST_state_mkFSMstate;
  MOD_Wire<tUInt8> INST_state_overlap_pw;
  MOD_Wire<tUInt8> INST_state_set_pw;
 
 /* Constructor */
 public:
  MOD_mktbCounter2(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_RL_action_l102c7;
  tUInt8 DEF_WILL_FIRE_RL_action_l101c11;
  tUInt8 DEF_WILL_FIRE_RL_action_l100c14;
  tUInt8 DEF_WILL_FIRE_RL_action_l99c14;
  tUInt8 DEF_WILL_FIRE_RL_action_l98c11;
  tUInt8 DEF_WILL_FIRE_RL_action_l97c14;
 
 /* Local definitions */
 private:
  tUInt8 DEF_x_read__h334;
  tUInt8 DEF_counter_value_EQ_42___d54;
  tUInt8 DEF_NOT_counter_value_EQ_42_4___d55;
 
 /* Rules */
 public:
  void RL_counter_do_increment();
  void RL_counter_do_decrement();
  void RL_start_reg__dreg_update();
  void RL_state_handle_abort();
  void RL_state_fired__dreg_update();
  void RL_state_every();
  void RL_restart();
  void RL_action_l97c14();
  void RL_action_l98c11();
  void RL_action_l99c14();
  void RL_action_l100c14();
  void RL_action_l101c11();
  void RL_action_l102c7();
  void RL_idle_l96c15();
  void RL_fsm_start();
  void RL_auto_start();
  void RL_auto_finish();
  void __me_check_7();
  void __me_check_8();
  void __me_check_9();
  void __me_check_10();
  void __me_check_11();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mktbCounter2 &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mktbCounter2 &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mktbCounter2 &backing);
};

#endif /* ifndef __mktbCounter2_h__ */
