/*
 * Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
 * 
 * On Sat Apr 14 16:53:00 UTC 2018
 * 
 */
#include "bluesim_primitives.h"
#include "mktbCounter.h"


/* String declarations */
static std::string const __str_literal_2("Finished Simulations", 20u);
static std::string const __str_literal_1("The number is %0d", 17u);


/* Constructor */
MOD_mktbCounter::MOD_mktbCounter(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_counter(simHdl, "counter", this),
    INST_state(simHdl, "state", this, 16u, 0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u)
{
  symbol_count = 5u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mktbCounter::init_symbols_0()
{
  init_symbol(&symbols[0u], "counter", SYM_MODULE, &INST_counter);
  init_symbol(&symbols[1u], "RL_state0", SYM_RULE);
  init_symbol(&symbols[2u], "RL_state1", SYM_RULE);
  init_symbol(&symbols[3u], "RL_state2", SYM_RULE);
  init_symbol(&symbols[4u], "state", SYM_MODULE, &INST_state);
}


/* Rule actions */

void MOD_mktbCounter::RL_state0()
{
  INST_counter.METH_load((tUInt8)10u);
  INST_state.METH_write(1u);
}

void MOD_mktbCounter::RL_state1()
{
  tUInt8 DEF_x_read__h50;
  DEF_x_read__h50 = INST_counter.METH_read();
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,8", &__str_literal_1, DEF_x_read__h50);
  INST_state.METH_write(2u);
}

void MOD_mktbCounter::RL_state2()
{
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    dollar_display(sim_hdl, this, "s", &__str_literal_2);
    dollar_finish(sim_hdl, "32", 0u);
  }
}


/* Methods */


/* Reset routines */

void MOD_mktbCounter::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_state.reset_RST(ARG_rst_in);
  INST_counter.reset_RST_N(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mktbCounter::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mktbCounter::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_counter.dump_state(indent + 2u);
  INST_state.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mktbCounter::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 2u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  num = INST_state.dump_VCD_defs(num);
  if (levels != 1u)
  {
    unsigned int l = levels == 0u ? 0u : levels - 1u;
    num = INST_counter.dump_VCD_defs(l);
  }
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mktbCounter::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mktbCounter &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
  if (levels != 1u)
    vcd_submodules(dt, levels - 1u, backing);
}

void MOD_mktbCounter::vcd_defs(tVCDDumpType dt, MOD_mktbCounter &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
    }
}

void MOD_mktbCounter::vcd_prims(tVCDDumpType dt, MOD_mktbCounter &backing)
{
  INST_state.dump_VCD(dt, backing.INST_state);
}

void MOD_mktbCounter::vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mktbCounter &backing)
{
  INST_counter.dump_VCD(dt, levels, backing.INST_counter);
}
