/*
 * Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
 * 
 * On Sat May  5 03:00:08 UTC 2018
 * 
 */
#include "bluesim_primitives.h"
#include "mktbCounterTest.h"


/* String declarations */
static std::string const __str_literal_1("The value of the Counter is: ", 29u);


/* Constructor */
MOD_mktbCounterTest::MOD_mktbCounterTest(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_counter(simHdl, "counter", this),
    INST_state(simHdl, "state", this, 2u, (tUInt8)0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u)
{
  symbol_count = 6u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mktbCounterTest::init_symbols_0()
{
  init_symbol(&symbols[0u], "counter", SYM_MODULE, &INST_counter);
  init_symbol(&symbols[1u], "RL_state1", SYM_RULE);
  init_symbol(&symbols[2u], "RL_state2", SYM_RULE);
  init_symbol(&symbols[3u], "RL_state3", SYM_RULE);
  init_symbol(&symbols[4u], "RL_state4", SYM_RULE);
  init_symbol(&symbols[5u], "state", SYM_MODULE, &INST_state);
}


/* Rule actions */

void MOD_mktbCounterTest::RL_state1()
{
  INST_counter.METH_setValue(20u);
  INST_state.METH_write((tUInt8)1u);
}

void MOD_mktbCounterTest::RL_state2()
{
  DEF_x_readVal__h59 = INST_counter.METH_readVal();
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,10", &__str_literal_1, DEF_x_readVal__h59);
  INST_counter.METH_increment(10u);
  INST_state.METH_write((tUInt8)2u);
}

void MOD_mktbCounterTest::RL_state3()
{
  DEF_x_readVal__h59 = INST_counter.METH_readVal();
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,10", &__str_literal_1, DEF_x_readVal__h59);
  INST_state.METH_write((tUInt8)3u);
}

void MOD_mktbCounterTest::RL_state4()
{
  INST_counter.METH_increment(10u);
}


/* Methods */


/* Reset routines */

void MOD_mktbCounterTest::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_state.reset_RST(ARG_rst_in);
  INST_counter.reset_RST_N(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mktbCounterTest::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mktbCounterTest::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_counter.dump_state(indent + 2u);
  INST_state.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mktbCounterTest::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 3u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x_readVal__h59", 10u);
  num = INST_state.dump_VCD_defs(num);
  if (levels != 1u)
  {
    unsigned int l = levels == 0u ? 0u : levels - 1u;
    num = INST_counter.dump_VCD_defs(l);
  }
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mktbCounterTest::dump_VCD(tVCDDumpType dt,
				   unsigned int levels,
				   MOD_mktbCounterTest &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
  if (levels != 1u)
    vcd_submodules(dt, levels - 1u, backing);
}

void MOD_mktbCounterTest::vcd_defs(tVCDDumpType dt, MOD_mktbCounterTest &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 10u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_x_readVal__h59) != DEF_x_readVal__h59)
      {
	vcd_write_val(sim_hdl, num, DEF_x_readVal__h59, 10u);
	backing.DEF_x_readVal__h59 = DEF_x_readVal__h59;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_x_readVal__h59, 10u);
      backing.DEF_x_readVal__h59 = DEF_x_readVal__h59;
    }
}

void MOD_mktbCounterTest::vcd_prims(tVCDDumpType dt, MOD_mktbCounterTest &backing)
{
  INST_state.dump_VCD(dt, backing.INST_state);
}

void MOD_mktbCounterTest::vcd_submodules(tVCDDumpType dt,
					 unsigned int levels,
					 MOD_mktbCounterTest &backing)
{
  INST_counter.dump_VCD(dt, levels, backing.INST_counter);
}
