/*
 * Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
 * 
 * On Sat May  5 03:00:08 UTC 2018
 * 
 */
#include "bluesim_primitives.h"
#include "model_mktbCounterTest.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mktbCounterTest::MODEL_mktbCounterTest()
{
  mktbCounterTest_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mktbCounterTest()
{
  MODEL_mktbCounterTest *model = new MODEL_mktbCounterTest();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mktbCounterTest &INST_top = *((MOD_mktbCounterTest *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_state__h116;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_state1;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_state1;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_state2;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_state2;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_state3;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_state3;
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_state4;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_state4;
	 INST_top.INST_counter.METH_RDY_setValue();
	 DEF_INST_top_DEF_state__h116 = INST_top.INST_state.METH_read();
	 DEF_INST_top_DEF_CAN_FIRE_RL_state1 = DEF_INST_top_DEF_state__h116 == (tUInt8)0u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_state1 = DEF_INST_top_DEF_CAN_FIRE_RL_state1;
	 INST_top.INST_counter.METH_RDY_increment();
	 DEF_INST_top_DEF_CAN_FIRE_RL_state2 = DEF_INST_top_DEF_state__h116 == (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_state2 = DEF_INST_top_DEF_CAN_FIRE_RL_state2;
	 DEF_INST_top_DEF_CAN_FIRE_RL_state3 = DEF_INST_top_DEF_state__h116 == (tUInt8)2u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_state3 = DEF_INST_top_DEF_CAN_FIRE_RL_state3;
	 DEF_INST_top_DEF_CAN_FIRE_RL_state4 = DEF_INST_top_DEF_state__h116 == (tUInt8)3u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_state4 = DEF_INST_top_DEF_CAN_FIRE_RL_state4;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_state1)
	   INST_top.RL_state1();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_state2)
	   INST_top.RL_state2();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_state3)
	   INST_top.RL_state3();
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_state4)
	   INST_top.RL_state4();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_counter.INST_counter.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_state.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mktbCounterTest::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mktbCounterTest_instance = new MOD_mktbCounterTest(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mktbCounterTest_instance->INST_counter.set_clk_0)("CLK");
  (mktbCounterTest_instance->set_clk_0)("CLK");
}
void MODEL_mktbCounterTest::destroy_model()
{
  delete mktbCounterTest_instance;
  mktbCounterTest_instance = NULL;
}
void MODEL_mktbCounterTest::reset_model(bool asserted)
{
  (mktbCounterTest_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mktbCounterTest::get_instance()
{
  return mktbCounterTest_instance;
}

/* Fill in version numbers */
void MODEL_mktbCounterTest::get_version(unsigned int *year,
					unsigned int *month,
					char const **annotation,
					char const **build)
{
  *year = 2016u;
  *month = 7u;
  *annotation = "beta1";
  *build = "34806";
}

/* Get the model creation time */
time_t MODEL_mktbCounterTest::get_creation_time()
{
  
  /* Sat May  5 03:00:08 UTC 2018 */
  return 1525489208llu;
}

/* Control run-time licensing */
tUInt64 MODEL_mktbCounterTest::skip_license_check()
{
  return 0llu;
}

/* State dumping function */
void MODEL_mktbCounterTest::dump_state()
{
  (mktbCounterTest_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mktbCounterTest & mktbCounterTest_backing(tSimStateHdl simHdl)
{
  static MOD_mktbCounterTest *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mktbCounterTest(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mktbCounterTest::dump_VCD_defs()
{
  (mktbCounterTest_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mktbCounterTest::dump_VCD(tVCDDumpType dt)
{
  (mktbCounterTest_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mktbCounterTest_backing(sim_hdl));
}
