/*
 * Generated by Bluespec Compiler, version 2016.07.beta1 (build 34806, 2016-07-05)
 * 
 * On Thu May  3 12:19:59 UTC 2018
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkAttempt.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkAttempt::MODEL_mkAttempt()
{
  mkAttempt_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkAttempt()
{
  MODEL_mkAttempt *model = new MODEL_mkAttempt();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkAttempt &INST_top = *((MOD_mkAttempt *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_say_hello;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_say_hello;
	 DEF_INST_top_DEF_CAN_FIRE_RL_say_hello = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_say_hello = DEF_INST_top_DEF_CAN_FIRE_RL_say_hello;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_say_hello)
	   INST_top.RL_say_hello();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_ctr.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkAttempt::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkAttempt_instance = new MOD_mkAttempt(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkAttempt_instance->set_clk_0)("CLK");
}
void MODEL_mkAttempt::destroy_model()
{
  delete mkAttempt_instance;
  mkAttempt_instance = NULL;
}
void MODEL_mkAttempt::reset_model(bool asserted)
{
  (mkAttempt_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkAttempt::get_instance()
{
  return mkAttempt_instance;
}

/* Fill in version numbers */
void MODEL_mkAttempt::get_version(unsigned int *year,
				  unsigned int *month,
				  char const **annotation,
				  char const **build)
{
  *year = 2016u;
  *month = 7u;
  *annotation = "beta1";
  *build = "34806";
}

/* Get the model creation time */
time_t MODEL_mkAttempt::get_creation_time()
{
  
  /* Thu May  3 12:19:59 UTC 2018 */
  return 1525349999llu;
}

/* Control run-time licensing */
tUInt64 MODEL_mkAttempt::skip_license_check()
{
  return 0llu;
}

/* State dumping function */
void MODEL_mkAttempt::dump_state()
{
  (mkAttempt_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkAttempt & mkAttempt_backing(tSimStateHdl simHdl)
{
  static MOD_mkAttempt *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkAttempt(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkAttempt::dump_VCD_defs()
{
  (mkAttempt_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkAttempt::dump_VCD(tVCDDumpType dt)
{
  (mkAttempt_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkAttempt_backing(sim_hdl));
}
